### ISSUE TITLE
Out of stock: Assembled Controller Circuit

### ISSUE THREAD

**Issue by x011** [jgillula/rpi-gate-opener#2]
Is there any chance that you can add stock so I can order a Assembled Controller Circuit from tindie? 
Thank you

**Comment by jgillula** [comment]
Sorry for the delay in responding--I just added stock. I don't currently have all the parts handy at home to build more since this is just a hobby (not really a business). :-)

But as soon as you place the order I'll go ahead and order all the parts I need. They should arrive during the week, and then I should be able to build it next weekend and have it shipped off to you.

**Comment by jgillula** [comment]
It looks like Tindie expects me to ship things out within 14 days, which is kind of tight (especially if there are long weekends in the middle). Going forward I'll probably just wait to order parts until somebody adds themselves to the waitlist, and then I'll indicate they're back in stock once the parts arrive.
